---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ci:
    name: Run the integration tests
    runs-on: ubuntu-latest

    steps:
      # cache pulled docker images
      - uses: ScribeMD/docker-cache@0.3.3
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('integration_tests/test_cnf_binary.py') }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'

      - run: |
          pip install --upgrade poetry
          poetry install

      - run: poetry run pytest -vv -n auto
