---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ci:
    name: Run the integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'poetry'

      - run: |
          pip install --upgrade poetry
          poetry install

      - run: poetry run pytest -vv -n auto
